# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MachineLearning.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MachineLearning.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15MachineLearning.proto\x12\x07\x65xample\"\x1c\n\x0bSendRequest\x12\r\n\x05param\x18\x01 \x01(\t\"\x1a\n\x08GetReply\x12\x0e\n\x06result\x18\x01 \x01(\t2J\n\x0fMachineLearning\x12\x37\n\nStartLearn\x12\x14.example.SendRequest\x1a\x11.example.GetReply\"\x00\x62\x06proto3')
)




_SENDREQUEST = _descriptor.Descriptor(
  name='SendRequest',
  full_name='example.SendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='param', full_name='example.SendRequest.param', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=62,
)


_GETREPLY = _descriptor.Descriptor(
  name='GetReply',
  full_name='example.GetReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='example.GetReply.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['SendRequest'] = _SENDREQUEST
DESCRIPTOR.message_types_by_name['GetReply'] = _GETREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendRequest = _reflection.GeneratedProtocolMessageType('SendRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDREQUEST,
  '__module__' : 'MachineLearning_pb2'
  # @@protoc_insertion_point(class_scope:example.SendRequest)
  })
_sym_db.RegisterMessage(SendRequest)

GetReply = _reflection.GeneratedProtocolMessageType('GetReply', (_message.Message,), {
  'DESCRIPTOR' : _GETREPLY,
  '__module__' : 'MachineLearning_pb2'
  # @@protoc_insertion_point(class_scope:example.GetReply)
  })
_sym_db.RegisterMessage(GetReply)



_MACHINELEARNING = _descriptor.ServiceDescriptor(
  name='MachineLearning',
  full_name='example.MachineLearning',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=92,
  serialized_end=166,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartLearn',
    full_name='example.MachineLearning.StartLearn',
    index=0,
    containing_service=None,
    input_type=_SENDREQUEST,
    output_type=_GETREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MACHINELEARNING)

DESCRIPTOR.services_by_name['MachineLearning'] = _MACHINELEARNING

# @@protoc_insertion_point(module_scope)
